### ISSUE TITLE
Is it dead?

### ISSUE THREAD

**Issue by Redo11** [ihucos/zpkg#8]
Did you already killed that project, or can we expect anything new?

**Comment by ihucos** [comment]
I think it is fair to say it's dead. Sometimes I experiment with it, but I do not have the resources to actively maintain it. Do you use it? Is it working for your use case?

**Comment by ihucos** [comment]
I did just create a release to use a newer fuse-overlayfs version. Turns out the older one was having a bug on my system.

**Comment by ihucos** [comment]
So is it dead? Lets call it a zombie!
